<a href="https://colab.research.google.com/github/AdithyaAjayakumar/learn.py/blob/main/TASK_10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Generate two  3 x 3 matrix and find it's dot product and take the transpose of the answer.

In [1]:
#please provide your answer below this line.
import numpy as np

M1 = np.array([[3, 6, 7], [5, 4, 6], [2, 3, 4]])
M2 = np.array([[9, 8, 3], [1, 2, 8], [6, 9, 2]])
M3 = M1.dot(M2)  
print("DOT PRODUCT")
print(M3)
print("TRANSPOSE")
M4 = M3.transpose()
print(M4)

DOT PRODUCT
[[ 75  99  71]
 [ 85 102  59]
 [ 45  58  38]]
TRANSPOSE
[[ 75  85  45]
 [ 99 102  58]
 [ 71  59  38]]


2. Create a 3x3 matrix with elements [55,25,15], [30,44,2], [11,45,77] . Now find the determinant of the given matrix.

In [2]:
#please provide your answer below this line.
import numpy as np

M1 = np.array([[55, 25, 15], [30, 44, 2], [11, 45, 77]])
print(M1)
A=np.linalg.det(M1)
print("determinant")
print(A)
b=round(np.linalg.det(M1))
print(b)

[[55 25 15]
 [30 44  2]
 [11 45 77]]
determinant
137180.0000000001
137180
