<a href="https://colab.research.google.com/github/AdithyaAjayakumar/learn.py/blob/main/TASK_8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Generate a 3 x 3 matrix using random module.

In [2]:
#please provide your answer below this line.
import numpy as np
matrix= np.random.randint(13, size=(3, 3))
print(matrix)

[[6 3 0]
 [8 5 7]
 [5 3 3]]


2. Generate two 4 x 4 matrix using numpy and 

 a) Reshape it to 2 x 8matrix and vertically stack it.

 b) Reshape it to 2 x 8 matrix and horizontally stack it.

In [1]:
#please provide your answer below this line.
import numpy as np
a1 = np.array([[1, 2, 3, 4], 
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]])
print("A1")
print(a1)
print("\n")
a1 = np.arange(1, 17).reshape(2, -1)
print(a1)
print("\n")
a2 = np.array([[1, 2, 3, 4], 
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]])
print("A2")
print(a2)
a2 = np.arange(1, 17).reshape(2, -1)
print("\n")
print(a2)
x = np.array([1, 2, 3, 4, 5, 6, 7, 8])
y = np.array([9, 10, 11, 12, 13, 14, 15, 16])
print('Vertically stacked array:\n', np.vstack((x, y)))
print("\n")
print('horizontally stacked array:\n', np.hstack((x, y)))

A1
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]]


A2
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]]
Vertically stacked array:
 [[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]]


horizontally stacked array:
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
